### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ugikmat** [divisi-mobile-POROS/Jadwal-Ujian-FILKOM#4]
App crashing when navigating,
full report : 
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: poros.filkom.ub.jadwalujianfilkom, PID: 18121
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                      at poros.filkom.ub.jadwalujianfilkom.adapter.JadwalAdapter.<init>(JadwalAdapter.java:26)
                      at poros.filkom.ub.jadwalujianfilkom.fragment.JadwalFragment.getJadwalKu(JadwalFragment.java:102)
                      at poros.filkom.ub.jadwalujianfilkom.fragment.JadwalFragment.access$300(JadwalFragment.java:37)
                      at poros.filkom.ub.jadwalujianfilkom.fragment.JadwalFragment$1.onResponse(JadwalFragment.java:258)
                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5268)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by asamsulfat** [comment]
Thanks for creating issue and submit a PR.
